"""
Pydantic schemas for MediScout data models.

Defines type-safe data structures for documents, analysis results, and reports.
"""

from typing import Any, Dict, List, Literal, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class Document(BaseModel):
    """Represents a retrieved document from any source."""
    
    id: str = Field(..., description="Unique document identifier")
    source: Literal["user", "pubmed", "clinicaltrials", "scholar"] = Field(
        ..., description="Origin of the document"
    )
    title: str = Field(..., description="Document title")
    content: str = Field(..., description="Full text or abstract")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
    embedding: Optional[List[float]] = Field(None, description="Vector embedding")
    relevance_score: Optional[float] = Field(None, description="Similarity score")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "pmid:12345678",
                "source": "pubmed",
                "title": "Study on Drug X",
                "content": "Abstract text...",
                "metadata": {"authors": ["Smith J"], "year": 2024},
                "relevance_score": 0.85
            }
        }


class AnalysisResult(BaseModel):
    """Result of critical analysis for a single document."""
    
    document_id: str = Field(..., description="Reference to source document")
    summary: str = Field(..., description="Concise summary of findings")
    study_design: Optional[str] = Field(None, description="Type of study (RCT, observational, etc.)")
    key_findings: List[str] = Field(default_factory=list, description="Main conclusions")
    patient_population: Optional[str] = Field(None, description="Study population details")
    intervention: Optional[str] = Field(None, description="Treatment or intervention")
    outcomes: List[str] = Field(default_factory=list, description="Primary and secondary outcomes")
    statistical_significance: Optional[str] = Field(None, description="P-values or confidence intervals")
    reliability_score: float = Field(default=0.5, ge=0.0, le=1.0, description="Source credibility")
    contradictions: List[str] = Field(default_factory=list, description="Conflicting information found")
    limitations: List[str] = Field(default_factory=list, description="Study limitations")
    
    class Config:
        json_schema_extra = {
            "example": {
                "document_id": "pmid:12345678",
                "summary": "RCT showing Drug X reduces symptoms",
                "study_design": "Randomized Controlled Trial",
                "key_findings": ["50% symptom reduction", "Well tolerated"],
                "reliability_score": 0.9
            }
        }


class Hypothesis(BaseModel):
    """A novel hypothesis generated from synthesized evidence."""
    
    id: str = Field(..., description="Unique hypothesis identifier")
    statement: str = Field(..., description="The hypothesis itself")
    reasoning_chain: List[str] = Field(..., description="Step-by-step reasoning")
    supporting_evidence: List[str] = Field(..., description="Document IDs supporting this hypothesis")
    confidence: Literal["low", "medium", "high"] = Field(..., description="Confidence level")
    testable_prediction: Optional[str] = Field(None, description="How to test this hypothesis")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "hyp_001",
                "statement": "Drug X may be effective for off-label use Y",
                "reasoning_chain": ["Step 1: Evidence A", "Step 2: Evidence B"],
                "supporting_evidence": ["pmid:123", "pmid:456"],
                "confidence": "medium"
            }
        }


class Report(BaseModel):
    """Final research report generated by the system."""
    
    research_topic: str = Field(..., description="Original research query")
    generated_at: datetime = Field(default_factory=datetime.now, description="Timestamp")
    executive_summary: str = Field(..., description="High-level overview")
    methods: str = Field(..., description="How the research was conducted")
    detailed_findings: str = Field(..., description="Comprehensive analysis results")
    contradictions_and_gaps: str = Field(..., description="Identified conflicts and research gaps")
    generated_hypotheses: List[Hypothesis] = Field(default_factory=list, description="Novel insights")
    sources_cited: List[str] = Field(..., description="All references used")
    document_count: int = Field(..., description="Number of documents analyzed")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional report metadata")
    
    class Config:
        json_schema_extra = {
            "example": {
                "research_topic": "Efficacy of Drug X for Disease Y",
                "executive_summary": "Analysis of 15 studies shows...",
                "document_count": 15
            }
        }


class QueryValidation(BaseModel):
    """Result of query validation."""
    
    is_valid: bool = Field(..., description="Whether query is valid")
    refined_query: str = Field(..., description="Improved or original query")
    suggestions: List[str] = Field(default_factory=list, description="Suggestions for improvement")
    medical_terms: List[str] = Field(default_factory=list, description="Extracted medical terms")
    
    class Config:
        json_schema_extra = {
            "example": {
                "is_valid": True,
                "refined_query": "efficacy of metformin for type 2 diabetes",
                "medical_terms": ["metformin", "type 2 diabetes"]
            }
        }


class RetrievalResult(BaseModel):
    """Combined retrieval results from all sources."""
    
    query: str = Field(..., description="Original search query")
    user_documents: List[Document] = Field(default_factory=list, description="From knowledge base")
    pubmed_documents: List[Document] = Field(default_factory=list, description="From PubMed")
    total_count: int = Field(..., description="Total documents retrieved")
    sources_used: List[str] = Field(..., description="Which sources were queried")
    retrieval_time_seconds: float = Field(..., description="Time taken")
    
    @property
    def all_documents(self) -> List[Document]:
        """Get all documents combined."""
        return self.user_documents + self.pubmed_documents
    
    class Config:
        json_schema_extra = {
            "example": {
                "query": "drug efficacy",
                "total_count": 15,
                "sources_used": ["user", "pubmed"],
                "retrieval_time_seconds": 2.5
            }
        }

